server:
  port: 9000
  servlet:
    context-path: /blog
spring:
  application:
    name: blogging_platform
  datasource:
    url: jdbc:mysql://localhost:3306/blog_posts
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update