
server:
  port: 9000
  servlet:
    context-path: /blog
spring:
  application:
    name: blogging_platform
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:blog_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    header:
      string: Authorization
    token:
      validity: 3600
      prefix: Bearer
    signing:
      key: 9a39863c912d9d310f5c4fd043ac9d4c1a4114fc39033ecb41b5d249092f6b1f
    authorities:
      key: roles
